apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ip8vk0bmt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip8vk0bmt-go 
  name: ip8vk0bmt-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ip8vk0bmt-go
    weight: 100 
