apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ip8vk0bmt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip8vk0bmt-go 
  name: ip8vk0bmt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ip8vk0bmt-go 
